#!/usr/bin/env bash
# Serve a web page using nginx
apt update -y
apt install -y nginx

echo "Hello World!" > /var/www/html/index.html

REDIRECT="\\\trewrite ^/redirect_me https://github.com/calvean permanent;"
sed -i "24i $REDIRECT" /etc/nginx/sites-available/default

service nginx restart
