#!/usr/bin/env bash
# Setting haproxy as load balancer
sudo apt-get update
sudo apt-get -y install haproxy
printf "\nfrontend 67841-lb-01\n
\tbind *:80\n
\tmode http\n
\toption forwardfor\n
\tdefault_backend servers\n\n
backend servers\n\
\tbalance roundrobin\n
\tserver 67841-web-01 54.237.46.86:80\n
\tserver 67841-web-02 54.173.174.117:80\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
