#!/usr/bin/env bash
#display conditions usinf while loop, if , elif, else conditions

((i=0))
while ((i<10))
do
  if [ $i -eq 3 ]
  then
    echo 'bad luck'
  elif [ $i -eq 7 ]
  then
    echo 'good luck'
  else
    echo 'Best School'
  fi
  ((i++))
done
