#!/usr/bin/env bash
# Install the ufw firewall and setup rules
apt upgrade -y
apt install ufw -y
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw default deny incoming
ufw default allow outgoing
ufw allow http
ufw allow ssh
ufw allow https
ufw enable
