#!/usr/bin/env bash

# Get the PID of the Gunicorn master process
MASTER_PID=$(cat /home/ubuntu/AirBnB_clone_v4/gunicorn.pid)

# Gracefully restart all workers by sending the HUP signal to the master process
kill -HUP "$MASTER_PID"

